### ISSUE TITLE
Incorporate resolutions of TTML1 issues.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#302]
This is an umbrella issue to cover the tasks of incorporating resolutions of TTML1 issues into TTML2.

- [x] [w3c/ttml1/#205](https://github.com/w3c/ttml1/issues/205) padding percentage
- [x] [w3c/ttml1/#221](https://github.com/w3c/ttml1/issues/221) padding and extent
- [x] [w3c/ttml1/#235](https://github.com/w3c/ttml1/issues/235) tab semantics
- [x] [w3c/ttml1/#237](https://github.com/w3c/ttml1/issues/237) references to CSS2
- [x] [w3c/ttml1/#239](https://github.com/w3c/ttml1/issues/239) tts:overflow

**Comment by skynavga** [comment]
Completed sub-tasks.
