### ISSUE TITLE
Incorporate resolutions of additional TTML1 Issues.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#358]
This is an umbrella issue to cover the tasks of incorporating resolutions of additional TTML1 issues into TTML2.

- [x] [w3c/ttml1/#191](https://github.com/w3c/ttml1/issues/191) drop mode forumla
- [x] [w3c/ttml1/#192](https://github.com/w3c/ttml1/issues/192) frame rate multiplier defaulting
- [x] [w3c/ttml1/#193](https://github.com/w3c/ttml1/issues/193) implicit duration span
- [x] [w3c/ttml1/#196](https://github.com/w3c/ttml1/issues/196) attribute forward compatibility
- [x] [w3c/ttml1/#197](https://github.com/w3c/ttml1/issues/197) pruning br erroneously
- [x] [w3c/ttml1/#201](https://github.com/w3c/ttml1/issues/201) agent and actor references
- [x] [w3c/ttml1/#204](https://github.com/w3c/ttml1/issues/204) generic family name
- [x] [w3c/ttml1/#205](https://github.com/w3c/ttml1/issues/205) clarify meaning of percentage
- [x] [w3c/ttml1/#207](https://github.com/w3c/ttml1/issues/207) visibility hidden
- [x] [w3c/ttml1/#212](https://github.com/w3c/ttml1/issues/212) content bpd
- [x] [w3c/ttml1/#214](https://github.com/w3c/ttml1/issues/214) font size using 'em' unit
- [x] [w3c/ttml1/#235](https://github.com/w3c/ttml1/issues/235) tab processing
- [x] [w3c/ttml1/#239](https://github.com/w3c/ttml1/issues/239) region overflow semantics
- [x] [w3c/ttml1/#241](https://github.com/w3c/ttml1/issues/241) z index auto
- [x] [w3c/ttml1/#251](https://github.com/w3c/ttml1/issues/251) not yet defined TT attributes
- [x] [w3c/ttml1/#266](https://github.com/w3c/ttml1/issues/266) epoch
- [x] [w3c/ttml1/#275](https://github.com/w3c/ttml1/issues/275) chained referential styling
- [x] [w3c/ttml1/#304](https://github.com/w3c/ttml1/issues/304) smooth scroll preference
- [x] [w3c/ttml1/#310](https://github.com/w3c/ttml1/issues/310) implicit durations of set
- [x] w3c/ttml1#316 fix typo
- [x] [w3c/ttml1/#320](https://github.com/w3c/ttml1/issues/320) overflow example

**Comment by cconcolato** [comment]
Adding:
- [ ] [w3c/ttml1/#275](https://github.com/w3c/ttml1/issues/275) Chained Referential Styling

**Comment by skynavga** [comment]
Handing off to @cconcolato.

**Comment by skynavga** [comment]
Removed [w3c/ttml1/#194](https://github.com/w3c/ttml1/issues/194) multiple descendant regions per resolution https://github.com/w3c/ttml1/issues/194#issuecomment-358699209 to take no action in TTML1.

**Comment by cconcolato** [comment]
w3c/ttml1/#191 drop mode formula is already fixed

**Comment by cconcolato** [comment]
for https://github.com/w3c/ttml1/issues/207, TTML1 PR https://github.com/w3c/ttml1/pull/270 says it used the text from TTML2. I checked: no change necessary to TTML2.

**Comment by cconcolato** [comment]
https://github.com/w3c/ttml1/issues/212 was closed without action. I don't think any action is necessary on TTML2

**Comment by cconcolato** [comment]
https://github.com/w3c/ttml1/issues/239 was closed without change to TTML1. No action necessary for this one.

**Comment by cconcolato** [comment]
for https://github.com/w3c/ttml1/issues/241, there is already similar text in TTML2. No action necessary.

**Comment by cconcolato** [comment]
@skynavga has https://github.com/w3c/ttml1/issues/214 been addressed by https://github.com/w3c/ttml2/pull/336?

**Comment by palemieux** [comment]
Additional TTML1 resolved issues and matching commit per https://github.com/w3c/ttml2/issues/358#issuecomment-360498634 

- w3c/ttml1#251 -> https://github.com/w3c/ttml1/commit/a3c25852dab84610f7ee753f1a6dccbcadd3b003
- w3c/ttml1#310 and w3c/ttml1#193 -> https://github.com/w3c/ttml1/commit/62ca2217c48915a45ee2e7efc318d2e95dfe4677

**Comment by cconcolato** [comment]
For https://github.com/w3c/ttml1/issues/214, the text in TTML1 matches the one in TTML2, no change needed.

**Comment by cconcolato** [comment]
Removing [w3c/ttml1/#317](https://github.com/w3c/ttml1/issues/317) chained referential styling (continued) from the list as agreed during the call.

**Comment by skynavga** [comment]
Unchecking sub-tasks for PRs that have not yet been merged (otherwise it looks like all sub-tasks are complete).

**Comment by skynavga** [comment]
@palemieux why is this marked as blocks CR? if this is to satisfy TTML1 3e requirements, then that cannot be a reason to block TTML2 CR, since the latter is not dependent on the former

**Comment by skynavga** [comment]
Prematurely auto-closed by #602.

**Comment by skynavga** [comment]
All tasks complete, so closing.
