### ISSUE TITLE
Privacy review umbrella issue

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#405]
From the Privacy IG meeting [2017-07-27](https://www.w3.org/2017/07/27-privacy-minutes.html):

* [x] #402 Add to privacy section the Privacy of Preference text as in IMSC
* [x] #403 Add to privacy section text to explain that implementations that load external resources on demand just prior to their presentation time may give information about media consumption to the origin - see IMSC 1.0.1 section "Security and Privacy related to external images"
* [x] #404 Consider referencing Fetch/CORS semantics informatively

**Comment by tmichel07** [comment]
also summarized bu Nigel here
https://lists.w3.org/Archives/Public/public-tt/2017Jul/0069.html

**Comment by nigelmegitt** [comment]
Any objections to doing all of the things in this issue? I'm not exactly sure how to reference the Fetch spec in this context.

There was also additional feedback from the PING meeting a couple of weeks ago that we might have the cross-origin stuff wrong, because most UAs apparently do allow cross-origin image fetching by default.

**Comment by skynavga** [comment]
I would object to any reference to a WHATWG document, even informative. However, one way to avoid a direct reference is to do something like "equivalent to fetch behavior of [HTML5]" which in turn may reference a WHATWG document (I haven't checked).

**Comment by skynavga** [comment]
All tasks completed.
